### ISSUE TITLE
Nano stack IPv6 + Ethernet fragmentation issue

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/sal-stack-nanostack#11] opened 2016-04-28 13:39 UTC
When using the CoAP lib on the nano IPv6 stack with a wired Ethernet connection running the sal-driver-lwip-k64f-eth, packets with a  size >1510 bytes needs to be fragmented. The issue we see is that once a packet must be fragmented into more then one fragment, the first fragment is transferred over Ethenet, but 2nd fragment is not. Once we send again CoAP message, the 2nd fragment is transferred.   

# Some observations in Wireshark:

We send a CoAP message (size 1942 bytes). First fragment is transferred:
`5.222832	aabb::bc45:73ff:fe86:4bdc	aabb::30	IPv6	1510	IPv6 fragment (off=0 more=y ident=0xcbfa5229 nxt=17)`
The 2nd fragment is not transferred!

Next (after 4 seconds) we send again a Coap message of 1942 bytes. Because of this the missing 2nd fragment is transferred:
`9.282853	aabb::bc45:73ff:fe86:4bdc	aabb::30	IPv6	556	IPv6 fragment (off=1448 more=n ident=0xcbfa522a nxt=17)`

Followed by the first fragment of the last send CoAP message:
`9.297145	aabb::bc45:73ff:fe86:4bdc	aabb::30	CoAP	1510	CON, MID:499, POST, /rd?ep=Push-Button + Controller + Actuator - be:45:73:86:4b:dc&et=test&lt=3600&b=U (text/plain)
`

If more info is required, please feel free to contact me. Thanks in advance.

**Comment by kjbracey-arm** [comment] 2016-04-28 13:46
This sounds like a duplicate of https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/issues/9

Fixed yesterday by https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/pull/11

Don't think it's been published to Yotta yet though.

**Comment by kjbracey-arm** [comment] 2016-04-28 13:50
Note that sending IP datagrams greater than 1500 bytes is pushing your luck. IPv6 nodes are not required to accept datagrams larger than that. You shouldn't normally attempt this without prior agreement with the destination that they can process them. (Does CoAP offer a mechanism to negotiate this? You can of course just rely on prior designer knowledge of your peer's capabilities, I suppose).

Nanostack will happily transmit and fragments as large as you like (subject to RAM) if asked, but won't receive them unless you raise arm_nwk_ipv6_frag_mru() above 1500, at the cost of increased RAM usage.

**Comment by EduardPon** [comment] 2016-04-28 13:56
I have tested with your solution, (change of number TX descriptors), but that does not fixes the issue. 
I still believe the IPv6 stack causes the issue. The IPv6 lib holds back the fragment, so no issue with the Ethernet stack at this point. 

Yes, I'm aware that large datagrams are a no go. But the IPv6 nano stack code has defined the fragmentation size on 1510 bytes. So if this is too high, IPv6 library should lower it (we have no source code to build it by our selves).

**Comment by ciarmcom** [comment] 2016-04-28 16:14
ARM Internal Ref: ONME-2591

**Comment by kjbracey-arm** [comment] 2016-04-29 06:54
You actually said "sal-driver-lwip-k64f-eth". I hope you didn't mean that. You're not trying to run LWIP and Nanostack simultaneously over Ethernet with two drivers, are you? That's not supported.

Nanostack will fragment to 1500 byte IPv6 payload over Ethernet by default. It will lower that if it gets an RA specifying a lower MTU, or path MTU discovery kicks in (it receives ICMPv6 Packet Too Big for some destination).

I can't see any reason Nanostack would "hold back" a packet fragment. On the contrary, the usual problem (on Ethernet) is that is pushes them all too fast. All fragments for one datagram are placed into the packet queue in one go, and sent successively to the driver.  Unlike for radio drivers, where packets are sent one-at-a-time, waiting for a "success" callback, Ethernet drivers have to accept and queue those packets, and don't get an opportunity to "push back" against the stack.

I see now that you have misread your trace. The second fragment of the first transmission (ident=0xcbfa5229) wasn't delayed; it was never sent. The second packet you saw was from the second transmission (ident=0xcbfa522a). 

Nanostack actually transmits fragments in reverse order. I believe you saw "5229 frag 1; 522a frag 2; 522a frag 1".

Which I think actually answers the question. "5229 frag 2" was lost during address resolution. Nanostack only queues one packet per address while waiting for address resolution. So when the Ethernet module was asked to transmit two fragments in rapid succession for a new address, it dropped the first one.

RFC 4861:

>   While waiting for address resolution to complete, the sender MUST,
>   for each neighbor, retain a small queue of packets waiting for
>   address resolution to complete.  The queue MUST hold at least one
>   packet, and MAY contain more.  However, the number of queued packets
>   per neighbor SHOULD be limited to some small value.  When a queue
>   overflows, the new arrival SHOULD replace the oldest entry.  Once
>   address resolution completes, the node transmits any queued packets.

Nanostack is trying to minimise memory by not queuing more than 1 packet for address resolution. This normally causes no issues because standard protocols don't start off with something large that might need fragmenting. And otherwise they don't start off with a burst of datagrams. Both for exactly this resolution reason, and other slow-start issues to do with opening paths and circuits on weird link types. (Note that even if Nanostack sent both fragments, it's possible that you might see the same effect at the last-hop router performing address resolution, if the server was remote).

The problem wouldn't show up if you were talking to a host you've previously talked to, or via a router you'd previously used. This is particular to suddenly sending a fragmented packet as the first packet to a next-hop you've not talked to before. All subsequent packets should work.

Note that you might also see 1 packet lost due to path MTU discovery. If the next hop towards your server had an MTU less than 1500 (maybe a VPN tunnel) you would get your first big packet dropped by the router, which would send an ICMPv6 message telling Nanostack to fragment to something smaller.

Handily, in this case, due to Nanostack keeping the big initial fragment during address resolution, it would be the initial fragment of already-incomplete datagram 1 getting dropped, so datagram 2 would get through. You shouldn't end up dropping 2 datagrams in total in that scenario.

I would suggest not sending a large datagram as your first packet. If possible, IP fragmentation should be avoided in general - there are all sorts of annoying issues like this. CoAP blockwise transfer could be used to avoid it, and I think our CoAP library supports this to some extent.

**Comment by EduardPon** [comment] 2016-05-02 13:00
Thanks for the analysis. This clarified the issue I have a lot. 

The LWM2M client performs a registration first after a reboot. In some cases the registration data size exceeds the 1510 bytes.

I have made some test code that confirms your statements. Sending first a small CoAP datagram. Once this CoAP message is acknowledged by the destination application (address resolution must be finished then), a large datagram is transferred in fragments and reassembled flawless.

In my view the LWM2M client must handle 'large' registrations differently. I will open an issue in the LWM2M github ARMmbed/mbed-client with the request to perform a fragmentation less registration.

Thanks for your support.

**Comment by TuomoHautamaki** [comment] 2016-05-17 12:26
Hi @EduardPon , as the analysis have been provided and you have now created new issue to mbed-client, is it okay to close this one?

Regards,
Tuomo

**Comment by EduardPon** [comment] 2016-05-17 12:31
Yes, thanks.

**Closed** 2016-05-18 07:43 UTC
Labels: mirrored
